# Generated by Django 4.1.5 on 2023-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_user_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cat_won',
            field=models.JSONField(blank=True, max_length=10, null=True),
        ),
    ]
