# Generated by Django 4.1.5 on 2023-01-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_player_cat_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cat_won',
        ),
        migrations.AddField(
            model_name='player',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='num_comp_catagories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
