# Generated by Django 4.1.5 on 2023-01-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_cat_won_player_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=20)),
                ('completed_category', models.CharField(max_length=50)),
            ],
        ),
    ]
