# Generated by Django 4.1.5 on 2023-01-18 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_player_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='num_comp_catagories',
            new_name='num_comp_categories',
        ),
    ]
