# Generated by Django 4.1.5 on 2023-01-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_player_num_comp_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='completed_category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
