# Generated by Django 4.1.5 on 2023-01-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_player_completed_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='completed_category',
            field=models.CharField(default=',', max_length=1000),
        ),
    ]
